{{- if .Values.runner.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.runner.name }}-secret
  namespace: {{ .Values.runner.namespace }}
type: Opaque
data:
  # This is obtained after creating a collector in the JupiterOne UI.
  auth-token: {{ .Values.runner.authToken | b64enc }}
{{ end }}