apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupiterone-integration-operator-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.ownLabels" . | nindent 4 }}
    control-plane: controller-manager
    {{- with (include "chart.userLabels" (dict "ctx" . "specific" (.Values.controllerManager.deployment | default dict).labels) | trim) }}{{ . | nindent 4 }}{{ end }}
  {{- with (include "chart.annotations" (dict "ctx" . "specific" (.Values.controllerManager.deployment | default dict).annotations)) }}{{ . | nindent 2 }}{{ end }}
spec:
  replicas:  {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- with (include "chart.userAnnotations" (dict "ctx" . "specific" (.Values.controllerManager.pod | default dict).annotations) | trim) }}{{ . | nindent 8 }}{{ end }}
      labels:
        {{- include "chart.ownLabels" . | nindent 8 }}
        control-plane: controller-manager
        {{- with (include "chart.userLabels" (dict "ctx" . "specific" (.Values.controllerManager.pod | default dict).labels) | trim) }}{{ . | nindent 8 }}{{ end }}
    spec:
      containers:
        - name: manager
          args:
            {{- range .Values.controllerManager.container.args }}
            - {{ . }}
            {{- end }}
          command:
            - /manager
          image: {{ .Values.controllerManager.container.image.repository }}:{{ .Values.controllerManager.container.image.tag | default .Chart.AppVersion }}
          env:
            {{- range $key, $value := .Values.controllerManager.container.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_INTEGRATION_SERVICE_ACCOUNT
              value: {{ .Values.integration.serviceAccountName }}
            {{- with (include "chart.integrationJobServiceAccountName" .) }}
            - name: INTEGRATION_JOB_SERVICE_ACCOUNT
              value: {{ . | quote }}
            {{- end }}
            {{- if .Values.controllerManager.imageRegistry }}
            - name: IMAGE_REGISTRY
              value: {{ .Values.controllerManager.imageRegistry | quote }}
            {{- end }}
            {{- if .Values.controllerManager.disableImageSignatureCheck }}
            - name: DISABLE_IMAGE_SIGNATURE_CHECK
              value: "true"
            {{- end }}
            {{- with .Values.controllerManager.imagePullSecrets }}
            - name: IMAGE_PULL_SECRETS
              value: {{ . | toJson | quote }}
            {{- end }}
            {{- with .Values.controllerManager.jobResources }}
            - name: JOB_RESOURCES
              value: {{ . | toJson | quote }}
            {{- end }}
            {{- with (include "chart.jobOverrides" .) }}
            - name: JOB_OVERRIDES
              value: {{ . | quote }}
            {{- end }}
            {{- with (include "chart.commonLabelsJson" .) }}
            - name: COMMON_LABELS
              value: {{ . | quote }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.controllerManager.container.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.controllerManager.container.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.controllerManager.container.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.controllerManager.container.securityContext | nindent 12 }}
          {{- if and .Values.certmanager.enable .Values.metrics.enable }}
          volumeMounts:
            {{- if and .Values.metrics.enable .Values.certmanager.enable }}
            - name: metrics-certs
              mountPath: /tmp/k8s-metrics-server/metrics-certs
              readOnly: true
            {{- end }}
          {{- end }}
      securityContext:
        {{- toYaml .Values.controllerManager.securityContext | nindent 8 }}
      serviceAccountName: {{ .Values.controllerManager.serviceAccountName }}
      {{- with .Values.controllerManager.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.controllerManager.terminationGracePeriodSeconds }}
      {{- with .Values.controllerManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllerManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllerManager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if and .Values.certmanager.enable .Values.metrics.enable }}
      volumes:
        {{- if and .Values.metrics.enable .Values.certmanager.enable }}
        - name: metrics-certs
          secret:
            secretName: metrics-server-cert
        {{- end }}
      {{- end }}
