{{- if .Values.integration.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.integration.serviceAccountName }}
  namespace: {{ .Values.integration.serviceAccountNamespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- end }}
{{- end }} 