{{/* This file was auto-generated by chartgen. Do not edit manually. */}}

{{/*
A string map as quoted "key: value" lines, each starting with a newline. A key
with no value becomes "". Takes (dict "map" m).
*/}}
{{- define "integration.metadataLines" -}}
{{- range $k, $v := (.map | default dict) }}
{{ $k | quote }}: {{ ternary "" (toString $v) (kindIs "invalid" $v) | quote }}
{{- end }}
{{- end }}


{{/*
commonLabels or commonAnnotations without the keys left out for "use":
"metadata" drops helm.sh/ and meta.helm.sh/ annotations (Helm acts on them);
"job" also drops keys the operator manages on the objects it creates for runs.
Takes (dict "map" m "annotation" bool "use" "metadata"|"job").
*/}}
{{- define "integration.commonMap" -}}
{{- $annotation := .annotation -}}
{{- $job := eq .use "job" -}}
{{- $reserved := list "app.kubernetes.io/name" "log-watcher" "job-name" "controller-uid" -}}
{{- $out := dict -}}
{{- range $k, $v := (.map | default dict) -}}
{{- $skip := and $annotation (or (hasPrefix "helm.sh/" $k) (hasPrefix "meta.helm.sh/" $k)) -}}
{{- if and $job (or (has $k $reserved) (hasPrefix "batch.kubernetes.io/" $k) (hasPrefix "integrations.jupiterone.io/" $k)) -}}
{{- $skip = true -}}
{{- end -}}
{{- if not $skip -}}
{{- $_ := set $out $k $v -}}
{{- end -}}
{{- end -}}
{{- $out | toJson -}}
{{- end }}


{{/*
labels: and annotations: blocks from commonLabels and commonAnnotations, for an
object's metadata, or nothing.
*/}}
{{- define "integration.metadata" -}}
{{- $labels := .Values.commonLabels | default dict -}}
{{- $annotations := include "integration.commonMap" (dict "map" .Values.commonAnnotations "annotation" true "use" "metadata") | fromJson -}}
{{- with (include "integration.metadataLines" (dict "map" $labels) | trim) }}
labels:
  {{- . | nindent 2 }}
{{- end }}
{{- with (include "integration.metadataLines" (dict "map" $annotations) | trim) }}
annotations:
  {{- . | nindent 2 }}
{{- end }}
{{- end }}


{{/*
The IntegrationInstance spec.job block, or nothing when empty. jobLabels and
podLabels are merged over commonLabels, jobAnnotations and podAnnotations over
commonAnnotations; the specific values win on the same key.
*/}}
{{- define "integration.job" -}}
{{- $labels := include "integration.commonMap" (dict "map" .Values.commonLabels "use" "job") | fromJson -}}
{{- $annotations := include "integration.commonMap" (dict "map" .Values.commonAnnotations "annotation" true "use" "job") | fromJson -}}
{{- $layers := dict
  "labels" (list $labels .Values.jobLabels)
  "annotations" (list $annotations .Values.jobAnnotations)
  "podLabels" (list $labels .Values.podLabels)
  "podAnnotations" (list $annotations .Values.podAnnotations) -}}
{{- $body := "" -}}
{{- range $field := list "annotations" "labels" "podAnnotations" "podLabels" -}}
{{- $m := dict -}}
{{- range $layer := (get $layers $field) -}}
{{- range $k, $v := ($layer | default dict) -}}
{{- $_ := set $m $k $v -}}
{{- end -}}
{{- end -}}
{{- with (include "integration.metadataLines" (dict "map" $m) | trim) -}}
{{- $body = printf "%s\n%s:%s" $body $field (. | nindent 2) -}}
{{- end -}}
{{- end -}}
{{- with ($body | trim) -}}
job:
  {{- . | nindent 2 }}
{{- end -}}
{{- end }}
