apiVersion: {{ template "cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{ template "graph-kubernetes.fullname" . }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    metadata:
    {{- with .Values.jobAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "graph-kubernetes.labels" . | nindent 8 }}
    {{- with .Values.jobLabels }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit | default 5 }}
      template:
        {{- if or .Values.podAnnotations .Values.podLabels }}
        metadata:
        {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.podLabels }}
          labels:
            {{- toYaml . | nindent 12 }}
        {{- end }} 
        {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          serviceAccountName: {{ include "graph-kubernetes.serviceAccountName" . }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ['bash', './scripts/run.sh']
              env:
                - name: ACCESS_TYPE
                  value: {{ ternary "cluster" "namespace" .Values.rbac.useClusterRole }}
                - name: NAMESPACE
                  value: {{ .Release.Namespace }}
                - name: JUPITERONE_ACCOUNT_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ (tpl .Values.existingSecret.name .) | default (include "graph-kubernetes.fullname" .) }}
                      key: {{ .Values.existingSecret.jupiteroneAccountIdSecretKey | default "jupiteroneAccountId" }}
                - name: JUPITERONE_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ (tpl .Values.existingSecret.name .) | default (include "graph-kubernetes.fullname" .) }}
                      key: {{ .Values.existingSecret.jupiteroneApiKeySecretKey | default "jupiteroneApiKey" }}
                - name: JUPITERONE_API_BASE_URL
                  value: {{ template "settings.baseApiUrl" . }}
                - name: INTEGRATION_INSTANCE_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ (tpl .Values.existingSecret.name .) | default (include "graph-kubernetes.fullname" .) }}
                      key: {{ .Values.existingSecret.jupiteroneIntegrationInstanceIdSecretKey | default "jupiteroneIntegrationInstanceId" }}
                - name: LOAD_KUBERNETES_CONFIG_FROM_DEFAULT
                  value: 'false'
              {{- if .Values.containerSecurityContext }}
              securityContext:
                {{- toYaml .Values.containerSecurityContext | nindent 16 }}
              {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          terminationGracePeriodSeconds: 60
