{{- if and .Values.rbac.create (eq .Values.rbac.useClusterRole false) (not .Values.rbac.useExistingRole) }}
{{- range $.Values.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "graph-kubernetes.fullname" . }}
  labels:
    {{- include "graph-kubernetes.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ''
    resources:
      - pods
      - namespaces
      - serviceaccounts
      - configmaps
      - nodes
      - services
      - secrets
    verbs:
      - list
  - apiGroups:
    - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs: 
      - list
  - apiGroups:
    - authorization.k8s.io
    resources:
      - selfsubjectaccessreviews
    verbs:
      - create
  - apiGroups:
    - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - list
  - apiGroups:
    - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - list
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - list
  - apiGroups: 
    - certificates.k8s.io
    resources: 
      - certificatesigningrequests
    verbs: 
      - get
      - list
      - watch
{{- end }}
{{- end }}
