{{- if .Values.integration.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ .Values.integration.serviceAccountName }}-integration-cluster
subjects:
  - kind: ServiceAccount
    name: {{ .Values.integration.serviceAccountName }}
    namespace: {{ .Values.integration.serviceAccountNamespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.integration.serviceAccountName }}-integration-cluster-readonly
  apiGroup: rbac.authorization.k8s.io
{{- end }}