{{- if and .Values.integration.jobServiceAccount.create (include "chart.integrationJobServiceAccountName" .) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.integrationJobServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with (include "chart.annotations" (dict "ctx" . "specific" .Values.integration.jobServiceAccount.annotations)) }}{{ . | nindent 2 }}{{ end }}
{{- end }}
