{{- if .Values.rbac.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: jupiterone-integration-operator-manager-role
rules:
- apiGroups:
  - integrations.jupiterone.io
  resources:
  - integrationinstancejobs
  - integrationrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integrations.jupiterone.io
  resources:
  - integrationinstancejobs/finalizers
  - integrationrunners/finalizers
  verbs:
  - update
- apiGroups:
  - integrations.jupiterone.io
  resources:
  - integrationinstancejobs/status
  - integrationrunners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - secrets  
  verbs:  
  - list
  - watch 
{{- end -}}
