{{- if .Values.rbac.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with (include "chart.annotations" (dict "ctx" . "specific" (.Values.controllerManager.serviceAccount | default dict).annotations)) }}{{ . | nindent 2 }}{{ end }}
  name: {{ .Values.controllerManager.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
