name: gitleaks

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code repository source code
        uses: actions/checkout@v2

      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master
